### PR TITLE
Fixes issue #1 'composer.json is overwritten when it is not valid'

### PR DESCRIPTION
**Pull request by graemetait**

### CODE REVIEW

**Comment by uzyn** [comment]
Thanks @burriko 

Mind resubmitting?

**Comment by graemetait** [comment]
Yeah, will do. For some reason the entire file was changed, when I only actually changed 2 lines! Wondering if there was an encoding problem, or maybe different line breaks. Weird.

**Comment by uzyn** [comment]
Just a wild guess are you on Windows?
It could be that Windows replaced all the EOL chars.

**Comment by graemetait** [comment]
Yeah, sadly I use a Windows PC at work. It was the Github for Windows app that caused it. I did the commit again from the command line and it worked fine.
Couldn't work out if I could change this pull request, so I've just resubmitted it.

**Pull request closed without merging**
